version: '3.0'
services:
  # MongoDB Services
  mongo_db_service:
    container_name: db_continer
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - mongo_db_service:/data/db

  # NodeJS API Service
  api_service:
    build: .
    ports: 
      - 3000:3000
    environment: 
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db_service:27017
      DB_NAME: blog_db
      NAME: TEST
    depends_on:
      - mongo_db_service 

volumes: 
  mongo_db_service: {}
